[package]
name = "Cratouille"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
ratatui = "0.30.0-alpha.0"
crossterm = "0.28.1"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
dirs = "5.0.1"
chrono = "0.4.39"
